TRUNCATE TABLE Info

INSERT INTO dbo.info(RandomCode, PlayerName, Desire, Tip1, Tip2, Tip3, Apply, Draw, Receiver)VALUES ('APC8YH','York','D','T1','T1','T1',0,0,0000)
INSERT INTO dbo.info(RandomCode, PlayerName, Desire, Tip1, Tip2, Tip3, Apply, Draw, Receiver)VALUES ('VAR8S5','耿丞','D','T2','T2','T2',0,0,0000)
INSERT INTO dbo.info(RandomCode, PlayerName, Desire, Tip1, Tip2, Tip3, Apply, Draw, Receiver)VALUES ('S5XZAC','慶偉','D','T3','T3','T3',0,0,0000)
INSERT INTO dbo.info(RandomCode, PlayerName, Desire, Tip1, Tip2, Tip3, Apply, Draw, Receiver)VALUES ('CLLAJF','偉正','D','T4','T4','T4',0,0,0000)
INSERT INTO dbo.info(RandomCode, PlayerName, Desire, Tip1, Tip2, Tip3, Apply, Draw, Receiver)VALUES ('UFLGVH','敏捷','D','T5','T5','T5',0,0,0000)
INSERT INTO dbo.info(RandomCode, PlayerName, Desire, Tip1, Tip2, Tip3, Apply, Draw, Receiver)VALUES ('5VFT8Z','陳境浩','D','T6','T6','T6',0,0,0000)
INSERT INTO dbo.info(RandomCode, PlayerName, Desire, Tip1, Tip2, Tip3, Apply, Draw, Receiver)VALUES ('PHTQH5','黃美琳','D','T7','T7','T7',0,0,0000)
INSERT INTO dbo.info(RandomCode, PlayerName, Desire, Tip1, Tip2, Tip3, Apply, Draw, Receiver)VALUES ('9Q8JDM','申禾','D','T8','T8','T8',0,0,0000)
INSERT INTO dbo.info(RandomCode, PlayerName, Desire, Tip1, Tip2, Tip3, Apply, Draw, Receiver)VALUES ('Q3AJJ9','仁凱','D','T9','T9','T9',0,0,0000)
INSERT INTO dbo.info(RandomCode, PlayerName, Desire, Tip1, Tip2, Tip3, Apply, Draw, Receiver)VALUES ('6A3FKQ','陳薪鴻','D','T10','T10','T10',0,0,0000)
INSERT INTO dbo.info(RandomCode, PlayerName, Desire, Tip1, Tip2, Tip3, Apply, Draw, Receiver)VALUES ('TVMDFJ','黃朝慶','D','T11','T11','T11',0,0,0000)
INSERT INTO dbo.info(RandomCode, PlayerName, Desire, Tip1, Tip2, Tip3, Apply, Draw, Receiver)VALUES ('LPX4EY','乃祥','D','T12','T12','T12',0,0,0000)
INSERT INTO dbo.info(RandomCode, PlayerName, Desire, Tip1, Tip2, Tip3, Apply, Draw, Receiver)VALUES ('YJGJJT','王文新','D','T13','T13','T13',0,0,0000)
INSERT INTO dbo.info(RandomCode, PlayerName, Desire, Tip1, Tip2, Tip3, Apply, Draw, Receiver)VALUES ('6CCRZF','茂伯','D','T14','T14','T14',0,0,0000)
INSERT INTO dbo.info(RandomCode, PlayerName, Desire, Tip1, Tip2, Tip3, Apply, Draw, Receiver)VALUES ('JEJA82','阿綠','D','T15','T15','T15',0,0,0000)
INSERT INTO dbo.info(RandomCode, PlayerName, Desire, Tip1, Tip2, Tip3, Apply, Draw, Receiver)VALUES ('BLHWGQ','CHC','D','T16','T16','T16',0,0,0000)
INSERT INTO dbo.info(RandomCode, PlayerName, Desire, Tip1, Tip2, Tip3, Apply, Draw, Receiver)VALUES ('2NTVV5','品叡大俠','D','T17','T17','T17',0,0,0000)
INSERT INTO dbo.info(RandomCode, PlayerName, Desire, Tip1, Tip2, Tip3, Apply, Draw, Receiver)VALUES ('6SJ4B5','HsinHan','D','T18','T18','T18',0,0,0000)
