//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Info
    {
        public int Id { get; set; }
        public string RandomCode { get; set; }
        public string PlayerName { get; set; }
        public string Desire { get; set; }
        public string Tip1 { get; set; }
        public string Tip2 { get; set; }
        public string Tip3 { get; set; }
        public bool Apply { get; set; }
        public bool Draw { get; set; }
        public int Receiver { get; set; }
    }
}
